name: Build and Deploy

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './vue/ikun/package-lock.json'

      - name: Install Dependencies
        working-directory: ./vue/ikun
        run: npm ci

      - name: Build Vue Project
        working-directory: ./vue/ikun
        run: npm run build

      - name: Generate Image List
        run: |
          chmod +x ./generate-pics-json.sh
          ./generate-pics-json.sh ./still ./vue/ikun/dist/pics.json

      - name: Create CNAME
        run: echo 'ikun.wcy.one' > ./vue/ikun/dist/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./vue/ikun/dist
          force_orphan: true